import bounds_effective_properties_solid_mechanics_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace bounds_effective_properties_solid_mechanics_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end bounds_effective_properties_solid_mechanics_theorem_canonical_lane_mathlib
end HautevilleHouse
